version: "3"

networks:
  backend:
    driver: "bridge"

volumes:
  postgres:
    driver: "local"

services:
  postgres:
    image: postgres:12
    volumes:
    - ./data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_DB=default
    - POSTGRES_USER=default
    - POSTGRES_PASSWORD=secret
    networks:
    - backend

  node:
    restart: "always"
    build: "."
    ports:
    - "8080:8080"
    environment:
      PORT: "8080"
    depends_on:
    - postgres
    networks:
    - backend
